# Generated by Django 3.0.5 on 2020-06-30 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choosers',
            field=models.ManyToManyField(related_name='chosen_choices', to=settings.AUTH_USER_MODEL),
        ),
    ]
