# Generated by Django 3.0.5 on 2020-07-04 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizapp', '0003_profile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='evaluated_users',
            field=models.ManyToManyField(related_name='evaluated_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
